### ISSUE TITLE
Question about the library

### ISSUE THREAD

**Issue by Daerius-rs** [jmoceri34/field-mapper#1]
@joemoceri
What exactly should be the final functionality of the library? I looked at the code and tests, but I didn't understand. Why not write a more general solution and support nesting and other things if you need to store a key/value in a string or just a lot of values in a string? I once implemented something similar in my library, although it probably doesn't work very well there (more in terms of performance)

**Comment by joemoceri** [comment]
@Daerius-rs I'll finish the documentation, update the tests, and explain more, but until then you can think of this as a tool that will parse form data as a string, if given keys (such as "First Name:", "Last Name:") and form data ("First Name: Joe Last Name: Moceri"). The result will be a dictionary with the following key-value pairs.

```csharp
// these two key-value pairs would be in the resulting dictionary after calling Get
{
"First Name:": "Joe",
"Last Name:": "Moceri"
}
```

Essentially this maps fields using the keys as markers to identify which values belong to which.

**Comment by Daerius-rs** [comment]
> form data ("First Name: Joe Last Name: Moceri")

This string should have this format? i.e. keys and values separated by a space? It is not yet clear to me what to do if the keys/values themselves have spaces, etc. (I believe that there will be escaping)
I just thought that maybe this is not some specific format of external data (i.e. "custom")

Again, as I said, I once faced a similar problem, to be more precise - I needed to have nesting support (store elements, arrays of elements and the same collections of elements) and the ability to create a string representation of the collection and restore the state from it
A few days later, I implemented the dictionary through the same "scheme".

So, it seemed to me that you can use something similar (although this is probably an overhead in some sense). If we talk about the code, it would be something like this:

```cs

var dictionary1 = new NestableDictionaryL<string>("Data")
{
    {"First Name", "Joe"},
    {"Last Name", "Moceri"}
};

var represent = dictionary1.ToStringRepresent();

Console.WriteLine(represent);
// {Data::NestableDictionaryL||"First Name::Joe","Last Name::Moceri"}

var dictionary2 = new NestableDictionaryL<string>();

dictionary2.FromStringRepresent(represent);

Console.WriteLine(dictionary2["First Name"].GetElement());
// Joe
Console.WriteLine(dictionary2["Last Name"].GetElement());
// Moceri

```

The average execution time is 52 ms. Of course, this is in my environment, but still it is not a normal benchmark, so the result is very approximate.
But the API, of course, is not so friendly.

Okay, I'll wait for new commits. Perhaps, if I understand the situation in more detail, I can even help in something and try to make a couple of pull requests.
However, thank you for your answer.

**Comment by joemoceri** [comment]
@Daerius-rs I appreciate the feedback, thank you. I'll update the documentation soon with more details.

**Comment by joemoceri** [comment]
@Daerius-rs Thanks again for the feedback, I updated the project overall, [here's a link to the FieldMapperTests.cs file](https://github.com/joemoceri/field-mapper-dotnet/blob/main/src/FieldMapperForDotNet.Tests/FieldMapperTests.cs) which outlines the usage for the library. The string data I was referring to comes from the body of an email, there are multiple email form providers that send plain-text / html form submission emails, and this library is built to handle that. For the future, the plan is to add more tests for different contact form submissions, and update the project as needed. Documentation is there, and more details to come.
